# Generated by Django 6.1.1 on 2026-10-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_contact_name_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershipinquiry',
            name='contact_name',
            field=models.CharField(max_length=150),
        ),
    ]
