# Generated by Django 6.1.1 on 2026-09-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='university',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
